import { MainLayout } from "@/components/MainLayout";
import { ServerStyleSheet } from "@/components/ServerStyleSheet";
import { Quicksand } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const quicksand = Quicksand({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <ServerStyleSheet>
          <MainLayout>{children}</MainLayout>
        </ServerStyleSheet>
      </body>
    </html>
  );
}
